# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Anthony Hamlin
title: Learning Omnivore | Occasional Dilettante
email: 
phone: 
website: https://hamberfim.github.io/

# Social links
twitter_username: jekyllrb
github_username:  jekyll
dribbble_username: jekyll
facebook_username: jekyll
flickr_username: jekyll
instagram_username: jekyll
linkedin_username: jekyll
xing_username: jekyll
pinterest_username: jekyll
youtube_username: jekyll
googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /arch_old_deployment/images/MeKandinsky.png
about_content: | # this will include new lines to allow paragraphs
  I create and translate concepts & static designs into responsive - dynamically functional websites using HTML, CSS, Python & other scripting languages. I'm intersted in building my skills as a full stack - backend developer with a focus in Python, SQL and Rest API's.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs

This is my personal recommendation for Anthony Hamlin. I was executive director of the Iowa Agriculture Innovation Center and directly supervised Anthony’s work at the Center for the last two years. Since the Center is closing, I wanted to ensure that you, as a potential employer for Anthony, would feel free to contact me at my new position regarding Anthony’s skills, knowledge and expertise. 

First, let me say that I wish I could have taken Anthony with me to the Iowa Department of Economic Development. I would happily re-employ Anthony as I considered him to be a valuable member of the Center’s team, who consistently achieved excellent results and always delivered, exceeding expectations. 

Anthony has been the Center’s Technology and Marketing Specialist and displayed a wide variety of skills and had in-depth expertise in all areas of the Center’s web presence including design and development, programming, and database development and integration into the website. Since the Center is closing down, the websites are discontinued but Anthony’s work was exceptional. 

Anthony is extremely knowledgeable and is easy to work with. He is able to explain complex IT issues and regulations in lay terms and enjoyed excellent working relationships with his customers – both internal and external. 

His design work was creative and innovative. He has a great sense of style, color and appropriateness. And is a dedicated worker who delivers quality results, every time. 

I highly recommend Anthony for employment. He is a team player and a leader. He would be a great asset to any organization. I really enjoyed working with such a skilled professional. 

Sincerely,

(Ret.) Pat Paustian
Executive Director - Iowa Agriculture Innovation Center,
Des Moines, IA 50319
I wanted to take this opportunity to give my recommendation for Anthony Hamlin. Anthony was a valuable member of the Iowa Interactive staff in the year I was able to work with him. 

The quality of Anthony's work was always excellent and I believe that he could be an asset to any company for which he worked. Anthony always completed tasks in a timely manner and the quality of his work was excellent. He worked hard and was able to give appropriate feedback and opinions when asked. He learned things which were out of his range of knowledge to assist the team in completing its work. 

He took his position very seriously and did an excellent job on the projects given to him. One of Anthony's greatest qualities was his sense of humor. He was able to fit into the office easily and was a pleasure to work with in the year that I worked with him. 

I am very hopeful that Anthony is successful in future endeavors and am very grateful for the work that he did while at Iowa Interactive. 

Sincerely,

Tim Erickson 
General Manager - Iowa Interactive, Inc., 
Des Moines, IA
Anthony Hamlin worked for Iowa Interactive, Inc., a sub-division of NIC, Inc., as a Web Designer/Developer. He reported directly to me, the Art Director. 

Anthony was responsible for creating and maintaining highly interactive websites for government agencies of the State of Iowa. Sites were delegated to Anthony to produce from beginning to end. His layouts were innovative and made navigation for the public as easy as possible. Our goal at Iowa Interactive, Inc., was for the public to be able to use state government services from their home or office, saving time and making it more convenient for people who could not make it to State offices. 

Anthony is very observant to what attracts people to a site. What they are going to be thinking while they are looking at a site, and anticipating what they will want to do next. 

Anthony and I were constantly showing each other sites and techniques that we had found on the web which we thought were eye catching, innovative, or improved techniques that we could use to further utilize the web for our surfers. Our main priorities were decreasing upload times and visual acceptance. Anthony also has an understanding of Java Script, CSS, HTML and orther web based technologies. Along with his strong print background Anthony became a very valuable asset to our staff. 

Our development team is in a small office and with small offices come close relationships. Anthony knew how to liven up the office with his humor. He got along great with everybody and was eager to help out in any way he could.

Regards,

Clint Clark 
Art Director/Director of Creative Content - Iowa Interactive, Inc. 
Des Moines, IA
It is a unique pleasure to write a few words of recommendation for/of Anthony D. Hamlin. I am always impressed not only with his sharp creativeness, the exactness of his photography and the excellent craftsmanship his mind & hands perform but more importantly his ability to communicate both visually & verbally. 

He has the ability to question and inspire at the same time. The quality of Anthony's work is always excellent and I believe that he will be an invaluable asset to any company that he works for.

Anthony can take a project from step one to completion without supervision and have it done correctly. He has an uncanny ability to communicate his wide range of knowledge to his peers and others to help them learn and complete their work. I am convinced that the well of creativeness and development of Anthony D. Hamlin has hardly been explored. 

Thank you for this opportunity,

Curtis Stahr 
(Ret.) Dir. Of Photography - DMACC, 
Ankeny, Iowa

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
